import math
import random

class Node:
    """A node in a search tree. Contains a pointer to the parent (the node
    that this is a successor of) and to the actual state for this node."""
    def __init__(self, state, parent=None, action=None, path_cost=0):
        self.state = state
        self.parent = parent
        self.action = action
        self.path_cost = path_cost

    def path(self):
        """Return a list of nodes forming the path from the root to this node."""
        node, path_back = self, []
        while node:
            path_back.append(node)
            node = node.parent
        return list(reversed(path_back))

    def __eq__(self, other):
        return isinstance(other, Node) and self.state == other.state

    def __hash__(self):
        # We use the hash value of the state.
        return hash(self.state)

class Problem:
    """The abstract class for a formal problem. You should subclass
    this and implement the methods actions and result, and possibly
    __init__, is_goal, and step_cost."""

    def __init__(self, initial_state, goal=None):
        self.initial_state = initial_state
        self.goal = goal

    def actions(self, state):
        """Return the actions that can be executed in the given state."""
        raise NotImplementedError

    def result(self, state, action):
        """Return the state that results from executing the given action in the given state."""
        raise NotImplementedError

    def is_goal(self, state):
        """Return True if the state is a goal."""
        return state == self.goal

    def step_cost(self, state, action, next_state):
        """Cost of taking action from state to next_state."""
        return 1
        
    def heuristic(self, state):
        """Estimated cost from state to goal."""
        return 0
        
    def value(self, state):
        """Value of a state (for local search algorithms)."""
        return 0

    def child_node(self, parent_node, action):
        """Returns the child node generated by applying action to parent_node."""
        next_state = self.result(parent_node.state, action)
        cost = parent_node.path_cost + self.step_cost(parent_node.state, action, next_state)
        return Node(next_state, parent_node, action, cost)

class Game:
    """A game is similar to a problem, but it has a utility for each
    state and a terminal test instead of a goal test. To create a game,
    subclass this class and implement actions, result, utility, and terminal_test."""

    def actions(self, state):
        """Return a list of the allowable moves at this point."""
        raise NotImplementedError

    def result(self, state, move):
        """Return the state that results from making a move from a state."""
        raise NotImplementedError

    def utility(self, state, player):
        """Return the value of this final state to player."""
        raise NotImplementedError

    def is_terminal(self, state):
        """Return True if this is a final state for the game."""
        return not self.actions(state)

class CSP:
    """This class describes finite-domain Constraint Satisfaction Problems.
    A CSP is specified by the following inputs:
        variables   A list of variables; each is atomic (e.g. int or string).
        domains     A dict of {var:[possible_value, ...]} entries.
        neighbors   A dict of {var:[var,...]} that for each variable lists
                    the other variables that participate in constraints.
        constraints A function f(A, a, B, b) that returns true if neighbors
                    A, B satisfy the constraint when they have values A=a, B=b"""

    def __init__(self, variables, domains, neighbors, constraints):
        self.variables = variables
        self.domains = domains
        self.neighbors = neighbors
        self.constraints = constraints
        self.initial_state = {}

    def is_consistent(self, var, value, assignment):
        """Return true if `value` is consistent with `assignment` for `var`."""
        for neighbor in self.neighbors[var]:
            if neighbor in assignment and not self.constraints(var, value, neighbor, assignment[neighbor]):
                return False
        return True

    def count_conflicts(self, var, value, assignment):
        """Return the number of conflicts `var`=`value` has with `assignment`."""
        count = 0
        for neighbor in self.neighbors[var]:
            if neighbor in assignment and not self.constraints(var, value, neighbor, assignment[neighbor]):
                count += 1
        return count
        
    def nconflicts(self, var, value, assignment):
        return self.count_conflicts(var, value, assignment)
        
    def assign(self, var, val, assignment):
        assignment[var] = val
        
    def unassign(self, var, assignment):
        if var in assignment:
            del assignment[var]
